"""empty message

Revision ID: 6db99a3dc28f
Revises: add808f87132
Create Date: 2018-04-14 22:20:07.167725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6db99a3dc28f'
down_revision = 'add808f87132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'library_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'library_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               nullable=False)
    # ### end Alembic commands ###
