"""empty message

Revision ID: 705a7a38ae3e
Revises: a53c9f916fbb
Create Date: 2018-04-17 13:05:27.421068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705a7a38ae3e'
down_revision = 'a53c9f916fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logtype', sa.String(length=20), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
