"""empty message

Revision ID: a53c9f916fbb
Revises: cba9f1869936
Create Date: 2018-04-15 02:16:55.219410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a53c9f916fbb'
down_revision = 'cba9f1869936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker_info', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('speaker_info', sa.Column('title', sa.String(length=256), nullable=False))
    op.alter_column('speaker_info', 'admin_approved',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('speaker_info', 'keynote_link',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('speaker_info', 'keynote_link',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('speaker_info', 'admin_approved',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.drop_column('speaker_info', 'title')
    op.drop_column('speaker_info', 'description')
    # ### end Alembic commands ###
