"""empty message

Revision ID: ad3c95a8a551
Revises: 
Create Date: 2018-04-11 16:30:59.069984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad3c95a8a551'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Libraries',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('location_road', sa.Text(), nullable=True),
    sa.Column('location_number', sa.Text(), nullable=True),
    sa.Column('location_detail', sa.Text(), nullable=True),
    sa.Column('manager_name', sa.Text(), nullable=True),
    sa.Column('manager_email', sa.Text(), nullable=True),
    sa.Column('manager_phone', sa.Text(), nullable=True),
    sa.Column('audiences', sa.Text(), nullable=True),
    sa.Column('fac_beam_screen', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('fac_sound', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('fac_record', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('fac_placard', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('fac_self_promo', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('fac_other', sa.Text(), nullable=True),
    sa.Column('req_speaker', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Libraries')
    # ### end Alembic commands ###
