"""empty message

Revision ID: cf9ae12b581b
Revises: 6db99a3dc28f
Create Date: 2018-04-14 22:24:08.439378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf9ae12b581b'
down_revision = '6db99a3dc28f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaker_info', 'has_experienced_somul')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker_info', sa.Column('has_experienced_somul', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
