"""empty message

Revision ID: df97c59fdf03
Revises: 09a02783f6cd
Create Date: 2018-04-14 21:32:03.675845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df97c59fdf03'
down_revision = '09a02783f6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker_info',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_time', sa.String(length=15), nullable=False),
    sa.Column('introduce', sa.Text(), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('keynote_link', sa.String(length=256), nullable=False),
    sa.Column('admin_approved', sa.String(length=30), nullable=False),
    sa.Column('has_experienced_somul', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speaker_info')
    # ### end Alembic commands ###
